#!/bin/bash
set -e

case "$1" in
    remove|upgrade)
        # 停止服务
        systemctl stop vernemq.service 2>/dev/null || true
        systemctl disable vernemq.service 2>/dev/null || true
        ;;
    deconfigure|failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
